# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wyver Academy
organisation: Wyver Solutions Ltd
orgurl: https://www.wyversolutions.co.uk
frameworkurl: https://digitallearningcompetencies.info
email: mberthelemy@wyversolutions.co.uk
description: Learn to become a learning technology consultant
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://wyversolutions.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme:
#plugins:
#  - jekyll-feed

collections:
    elearning-competencies:
        output: true
    challenges:
        output: true

defaults:
  - scope:
      path: ""
      type: "elearning-competencies"
    values:
      layout: "competency"
      permalink: /competencies/:title
  - scope:
      path: ""
      type: "challenges"
    values:
      layout: "challenge"

collections_dir: _collections

include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

levels:
    level1:
        ID: Level 1
        name: Digital Learning Foundation
    level2:
        ID: Level 2
        name: Digital Learning Practitioner
    level3:
        ID: Level 3
        name: Digital Learning Advanced
